-- Glow Dashboard PIN authentication foundation
-- Run this before using PIN login/reset controls.
-- This does NOT enable RLS yet. It prepares real staff/manager identity so RLS can be enabled safely later.

alter table "Staff"
add column if not exists pin_hash text,
add column if not exists pin_salt text,
add column if not exists pin_set_at timestamp with time zone,
add column if not exists login_active boolean default true,
add column if not exists last_login_at timestamp with time zone,
add column if not exists failed_login_attempts integer default 0;

create table if not exists "GlowAuditLogs" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  staff_id bigint,
  staff_name text,
  action text not null,
  details text,
  metadata jsonb default '{}'::jsonb
);

create index if not exists glow_audit_logs_created_at_idx on "GlowAuditLogs" (created_at desc);
create index if not exists glow_audit_logs_staff_id_idx on "GlowAuditLogs" (staff_id);
create index if not exists glow_audit_logs_action_idx on "GlowAuditLogs" (action);

comment on column "Staff".pin_hash is 'PBKDF2 SHA-256 hash of the 4-digit staff PIN. Never store the plain PIN.';
comment on column "Staff".pin_salt is 'Per-staff random salt used for PIN hashing.';
comment on table "GlowAuditLogs" is 'Dashboard audit trail for login, logout, booking edits, cash-up, receipt, export, and manager actions. RLS should protect this table before strict rollout.';
